target = hw3_1 hw3_2
CPPFLAGS = -O2 -g -std=c++11 -Wall

all: hw3_1 hw3_2

hw3_1: hw3_1.cpp
	g++ $(CPPFLAGS) hw3_1.cpp -o $@
hw3_2: hw3_2.cpp
	g++ $(CPPFLAGS) hw3_2.cpp -o $@
run3_1:
	./hw3_1
run3_2:
	./hw3_2
